// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBGygiFT3wfbUaDVoNA4ATo9tT9NzlZ690',
    appId: '1:803028287569:web:eb982f22de49c98e87f870',
    messagingSenderId: '803028287569',
    projectId: 'closetly-e3486',
    authDomain: 'closetly-e3486.firebaseapp.com',
    storageBucket: 'closetly-e3486.firebasestorage.app',
    measurementId: 'G-054VNWP2VS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDxnXTzXlIoauG0V3gHRtpTACwMnWzCFwU',
    appId: '1:803028287569:android:93ae74a73f88f17387f870',
    messagingSenderId: '803028287569',
    projectId: 'closetly-e3486',
    storageBucket: 'closetly-e3486.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBGygiFT3wfbUaDVoNA4ATo9tT9NzlZ690',
    appId: '1:803028287569:web:1661db78f5f4377187f870',
    messagingSenderId: '803028287569',
    projectId: 'closetly-e3486',
    authDomain: 'closetly-e3486.firebaseapp.com',
    storageBucket: 'closetly-e3486.firebasestorage.app',
    measurementId: 'G-1MWMC8766M',
  );
}
